// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPeMyQDL2y3deRsz3T7trWXqzf9u0sdoA',
    appId: '1:37884773488:android:975eef0b94903bfcf620b5',
    messagingSenderId: '37884773488',
    projectId: 'easy-power-hub',
    storageBucket: 'easy-power-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRjSHJ4HXK474e_yT63JqyotTFDTG5hGM',
    appId: '1:37884773488:ios:5ef16a69d293aaa8f620b5',
    messagingSenderId: '37884773488',
    projectId: 'easy-power-hub',
    storageBucket: 'easy-power-hub.firebasestorage.app',
    iosBundleId: 'com.echobitstech.easyph',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpJ7YlgHTCcvWm49Rko9vcwTvLqdLznMc',
    appId: '1:37884773488:web:26d284db59dde12ef620b5',
    messagingSenderId: '37884773488',
    projectId: 'easy-power-hub',
    authDomain: 'easy-power-hub.firebaseapp.com',
    storageBucket: 'easy-power-hub.firebasestorage.app',
    measurementId: 'G-HFKXKR1F5T',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRjSHJ4HXK474e_yT63JqyotTFDTG5hGM',
    appId: '1:37884773488:ios:b908b193c67f971bf620b5',
    messagingSenderId: '37884773488',
    projectId: 'easy-power-hub',
    storageBucket: 'easy-power-hub.firebasestorage.app',
    iosBundleId: 'com.example.wahalaHq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpJ7YlgHTCcvWm49Rko9vcwTvLqdLznMc',
    appId: '1:37884773488:web:351fa42f474781dff620b5',
    messagingSenderId: '37884773488',
    projectId: 'easy-power-hub',
    authDomain: 'easy-power-hub.firebaseapp.com',
    storageBucket: 'easy-power-hub.firebasestorage.app',
    measurementId: 'G-DQF6JSE86Z',
  );

}