// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7SzR7nNTjTkxXrK1IQnRRdU00W-UJM6U',
    appId: '1:875974620022:android:81a401add9720d1f140057',
    messagingSenderId: '875974620022',
    projectId: 'easy-ph',
    storageBucket: 'easy-ph.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKvRXM4jGYcr0wOZV9ot3Y8UrteRrvI_8',
    appId: '1:875974620022:ios:f1528dfad9c87ca7140057',
    messagingSenderId: '875974620022',
    projectId: 'easy-ph',
    storageBucket: 'easy-ph.firebasestorage.app',
    androidClientId: '875974620022-cnjh2q702m25k602gkuao6hc5o124ks6.apps.googleusercontent.com',
    iosClientId: '875974620022-ab75vd5sgukrjsgl48uvnq4tdr3vook3.apps.googleusercontent.com',
    iosBundleId: 'com.echobitstech.easyph',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvkBRvzIVtfsZF23_jdTLlBrFvDscR6E',
    appId: '1:875974620022:web:f84b0e3d101ca360140057',
    messagingSenderId: '875974620022',
    projectId: 'easy-ph',
    authDomain: 'easy-ph.firebaseapp.com',
    storageBucket: 'easy-ph.firebasestorage.app',
    measurementId: 'G-86Z9LZ60TS',
  );

}