// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzaB-bH7SSYuk8gwYVHU4zSzac0vrSWX0',
    appId: '1:875974620022:android:23548575c33fa1f3140057',
    messagingSenderId: '875974620022',
    projectId: 'easy-ph',
    storageBucket: 'easy-ph.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyUGhHAIlcIYqnjhBmLlY0N4278cWC8e8',
    appId: '1:875974620022:ios:abec2891c6522825140057',
    messagingSenderId: '875974620022',
    projectId: 'easy-ph',
    storageBucket: 'easy-ph.firebasestorage.app',
    iosBundleId: 'com.echobitstech.easyph',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvkBRvzIVtfsZF23_jdTLlBrFvDscR6E',
    appId: '1:875974620022:web:68c80dcda652ecd2140057',
    messagingSenderId: '875974620022',
    projectId: 'easy-ph',
    authDomain: 'easy-ph.firebaseapp.com',
    storageBucket: 'easy-ph.firebasestorage.app',
    measurementId: 'G-JNGCJPHTBV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyUGhHAIlcIYqnjhBmLlY0N4278cWC8e8',
    appId: '1:875974620022:ios:8c267787ba12a7a2140057',
    messagingSenderId: '875974620022',
    projectId: 'easy-ph',
    storageBucket: 'easy-ph.firebasestorage.app',
    iosBundleId: 'com.example.easyph',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqvkBRvzIVtfsZF23_jdTLlBrFvDscR6E',
    appId: '1:875974620022:web:92b50ae8f6d79538140057',
    messagingSenderId: '875974620022',
    projectId: 'easy-ph',
    authDomain: 'easy-ph.firebaseapp.com',
    storageBucket: 'easy-ph.firebasestorage.app',
    measurementId: 'G-VBXCX7SMKD',
  );

}